### ISSUE TITLE
How to use without delay provider

### ISSUE THREAD

**Issue by redeexpressos** [VersBinarii/bme280-rs#42]
Hi. I want to use this crate but it seems that `ìnit` needs a delay provider.

```
bme280::i2c::BME280
impl<I2C> BME280<I2C>
pub fn init<D>(&mut self, delay: &mut D) -> Result<(), Error<I2C::Error>>
where
    D: DelayNs,
    // Bounds from impl:
    I2C: I2c + ErrorType,
```

How can I provide, e.g, 1 second? Or init it without a `delay` and then I sleep in a `loop` after measuring? I want to run this on a small SoM computer running Linux, not a microcontroller/wtv.

**Comment by VersBinarii** [comment]
I believe you should be able to make it work with the Delay from [embedded linux hal](https://docs.rs/linux-embedded-hal/latest/linux_embedded_hal/struct.Delay.html)
