### ISSUE TITLE
Implement `std::error::Error` for public `Error` struct

### ISSUE THREAD

**Issue by nukemberg** [VersBinarii/bme280-rs#9]
Implementing the `std::error::Error` trait allows for error forwarding and interoperability with error handling libraries e.g. thiserror.

**Comment by nukemberg** [comment]
I see that since `#![no_std]` is used `std::error::Error` cannot be implemented. Is there any way to make this conditional? e.g. via features?

**Comment by VersBinarii** [comment]
There is a pull request https://github.com/VersBinarii/bme280-rs/pull/13 awaiting to address that.
I will merge it as soon as its rebased. If there is no response from author i will apply that change manually over the weekend.

**Comment by VersBinarii** [comment]
Closing this with https://github.com/VersBinarii/bme280-rs/pull/17
